# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_baseball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumpyDatsStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='csvs/')),
                ('key', models.CharField(max_length=14)),
            ],
        ),
    ]
