# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_baseball', '0002_numpydatsstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='numpydatsstructure',
            name='numpy_function',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drf_baseball.NumpyFunction'),
            preserve_default=False,
        ),
    ]
