# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_baseball', '0003_numpydatsstructure_numpy_function'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumpyDatsStructure',
            new_name='NumpyDataStructure',
        ),
    ]
